Task1
heli0dus/formal-lang-course pull request #1
Opened 2024-02-14 19:56 UTC by heli0dus

2024-03-01 09:24 UTC, WoWaster requested changes
Всё хорошо, поменяйте имя workflow только

2024-03-01 09:24 UTC, WoWaster commented on .github/workflows/tests.yml
> +name: Check code style
Переименуйте, пожалуйста, workflow, а то их потом не отличишь :(

2024-03-01 18:33 UTC, heli0dus commented on .github/workflows/tests.yml
> +name: Check code style
Я переименовал и оно умерло, я не понимаю, что пошло не так т.т

2024-03-01 18:36 UTC, WoWaster commented on .github/workflows/tests.yml
> +name: Check code style
У вас как-то очень странно ветка растёт, потому что я вижу 20+ коммитов из main, при том хеши у них совпадают. Могу предложить rebase, но это может привести к ещё большим страданиям

2024-03-01 18:38 UTC, heli0dus commented on .github/workflows/tests.yml
> +name: Check code style
я как раз rebase и сделал чтобы reqirements обновились
видимо зря

2024-03-01 18:38 UTC, WoWaster commented on .github/workflows/tests.yml
> +name: Check code style
!!!Что-то на продвинутом!!!
Возможно вам нужно используя git reflog вернуть старую версию ветки и попытаться аккуратнее перебазировать её от main.

2024-03-01 18:39 UTC, WoWaster commented on .github/workflows/tests.yml
> +name: Check code style
В любом случае смотреть на >1k измененных строчек я не буду, у меня глаза сломаются

2024-03-01 18:52 UTC, heli0dus commented on .github/workflows/tests.yml
> +name: Check code style
допустим этот кошмар я откатил
но пока все равно валится workflow после простого переименования

2024-03-02 11:54 UTC, WoWaster approved these changes

2024-03-11 10:19 UTC, merged