Task3
heli0dus/formal-lang-course pull request #3
Opened 2024-03-07 07:50 UTC by heli0dus

2024-03-07 08:06 UTC, heli0dus commented
Лучше поздно, чем никогда

2024-03-07 18:49 UTC, WoWaster requested changes
Давайте разберёмся с первыми двумя задачами -- в этой ветке оказались все три, поэтому пока проверять её не буду. Как починим первые две, запросите здесь новое ревью

2024-03-07 19:51 UTC, heli0dus commented on project/task3.py
> +def paths_ends(
В смысле path_ends нет((( 
Вот же оно

2024-03-08 10:02 UTC, WoWaster commented on project/task3.py
> +def paths_ends(
Извиняюсь, проглядел. Но остальные комментарии остаются в силе

2024-03-13 10:55 UTC, WoWaster approved these changes

2024-03-13 11:01 UTC, merged